from copy import deepcopy

CRITICAL_MARKERS = [
    "Cy",
    "Sb",
    "Tb",
    "Hu",
    "B",
    "Adc",
    "Bar",
    "Bl",
    "N",
    "Ki",
    "Pri",
    "w",
    "y",
    "ca",
    "e",
    "cn",
    "bw",
    "p",
    "red",
    "speck",
    "st",
    "vg",
    "Ser",
    "D",
    "Sp",
    "sn",
    "f",
    "ey",
    "v",
    "sc",
    "sev",
    "pr",
    "ry",
    "cu",
    "cv",
    "Dr",
    "L",
    "mwh",
    "al",
    "ct",
    "hry",
    "lt",
    "nub",
    "ru",
    "sr",
    "Ubx",
]


VISUAL_MARKER_DICTIONARY = {
    "Bar": {
        "body_part": "eye",
        "effect": "bar-shaped reduced eyes",
        "dominance": "dominant",
        "display_label": "Bar",
        "phenotype_key": "Bar",
        "chromosome": 1,
        "scoring_confidence": 0.9,
        "gene_name": "Bar",
        "flybase_id": "FBgn0000154",
        "reference_url": "https://flybase.org/reports/FBgn0000154.html",
        "source": "manual_dictionary",
    },
    "Bl": {
        "body_part": "bristle",
        "effect": "dominant abnormal macrochaetae",
        "dominance": "dominant",
        "display_label": "Bl",
        "phenotype_key": "Bl",
        "chromosome": 2,
        "scoring_confidence": 0.72,
        "gene_name": "Bristle",
        "flybase_id": "FBgn0000193",
        "reference_url": "https://flybase.org/reports/FBgn0000193.html",
        "source": "manual_dictionary",
    },
    "Dr": {
        "body_part": "eye",
        "effect": "drop-shaped reduced eyes",
        "dominance": "dominant",
        "display_label": "Dr",
        "phenotype_key": "Dr",
        "chromosome": 3,
        "scoring_confidence": 0.79,
        "gene_name": "Drop",
        "flybase_id": "FBgn0000492",
        "reference_url": "https://flybase.org/reports/FBgn0000492.html",
        "source": "manual_dictionary",
    },
    "D": {
        "body_part": "wing",
        "effect": "dominant Dichaete wing posture marker",
        "dominance": "dominant",
        "display_label": "D",
        "phenotype_key": "D",
        "chromosome": 3,
        "scoring_confidence": 0.78,
        "gene_name": "Dichaete",
        "flybase_id": "FBgn0000411",
        "reference_url": "https://flybase.org/reports/FBgn0000411.html",
        "source": "manual_dictionary",
    },
    "B": {
        "body_part": "eye",
        "effect": "bar-shaped eyes",
        "dominance": "dominant",
        "display_label": "B",
        "phenotype_key": "B",
        "chromosome": 1,
        "scoring_confidence": 0.92,
        "source": "manual_dictionary",
    },
    "Cy": {
        "body_part": "wing",
        "effect": "curly wings",
        "dominance": "dominant",
        "display_label": "Cy",
        "phenotype_key": "Cy",
        "chromosome": 2,
        "homozygous_lethal": True,
        "scoring_confidence": 0.98,
        "source": "manual_dictionary",
    },
    "Hu": {
        "body_part": "thorax",
        "effect": "humeral bristle marker",
        "dominance": "dominant",
        "display_label": "Hu",
        "phenotype_key": "Hu",
        "chromosome": 3,
        "scoring_confidence": 0.74,
        "source": "manual_dictionary",
    },
    "L": {
        "body_part": "eye",
        "effect": "lobed reduced eyes",
        "dominance": "dominant",
        "display_label": "L",
        "phenotype_key": "L",
        "chromosome": 2,
        "scoring_confidence": 0.84,
        "gene_name": "Lobe",
        "flybase_id": "FBgn0288433",
        "reference_url": "https://flybase.org/reports/FBgn0288433.html",
        "source": "manual_dictionary",
    },
    "Sb": {
        "body_part": "bristle",
        "effect": "short, thick bristles",
        "dominance": "dominant",
        "display_label": "Sb",
        "phenotype_key": "Sb",
        "chromosome": 3,
        "scoring_confidence": 0.94,
        "source": "manual_dictionary",
    },
    "Ser": {
        "body_part": "wing",
        "effect": "serrated wing margin",
        "dominance": "dominant",
        "display_label": "Ser",
        "phenotype_key": "Ser",
        "chromosome": 3,
        "scoring_confidence": 0.82,
        "source": "manual_dictionary",
    },
    "Tb": {
        "body_part": "body",
        "effect": "tubby body shape",
        "dominance": "dominant",
        "display_label": "Tb",
        "phenotype_key": "Tb",
        "chromosome": 3,
        "scoring_confidence": 0.8,
        "source": "manual_dictionary",
    },
    "Ubx": {
        "body_part": "haltere",
        "effect": "homeotic haltere-to-wing transformation",
        "dominance": "dominant",
        "display_label": "Ubx",
        "phenotype_key": "Ubx",
        "chromosome": 3,
        "scoring_confidence": 0.82,
        "gene_name": "Ultrabithorax",
        "flybase_id": "FBgn0003944",
        "reference_url": "https://flybase.org/reports/FBgn0003944.html",
        "source": "manual_dictionary",
    },
    "Adc": {
        "body_part": "body",
        "effect": "dark black body coloration",
        "dominance": "recessive",
        "display_label": "Adc",
        "phenotype_key": "Adc",
        "chromosome": 2,
        "scoring_confidence": 0.83,
        "gene_name": "Acidic amino acid decarboxylase",
        "flybase_id": "FBgn0000153",
        "reference_url": "https://flybase.org/reports/FBgn0000153.html",
        "source": "manual_dictionary",
    },
    "N": {
        "body_part": "wing",
        "effect": "notched wing margin",
        "dominance": "dominant",
        "display_label": "N",
        "phenotype_key": "N",
        "chromosome": 1,
        "scoring_confidence": 0.91,
        "gene_name": "Notch",
        "flybase_id": "FBgn0004647",
        "reference_url": "https://flybase.org/reports/FBgn0004647.html",
        "source": "manual_dictionary",
    },
    "Ki": {
        "body_part": "bristle",
        "effect": "kinked thoracic bristles",
        "dominance": "dominant",
        "display_label": "Ki",
        "phenotype_key": "Ki",
        "chromosome": 3,
        "scoring_confidence": 0.76,
        "gene_name": "Kinked",
        "flybase_id": "FBgn0001307",
        "reference_url": "https://flybase.org/reports/FBgn0001307.html",
        "source": "manual_dictionary",
    },
    "Pri": {
        "body_part": "bristle",
        "effect": "prickly thoracic bristles",
        "dominance": "dominant",
        "display_label": "Pri",
        "phenotype_key": "Pri",
        "chromosome": 3,
        "scoring_confidence": 0.74,
        "gene_name": "Prickly",
        "flybase_id": "FBgn0003142",
        "reference_url": "https://flybase.org/reports/FBgn0003142.html",
        "source": "manual_dictionary",
    },
    "al": {
        "body_part": "antenna",
        "effect": "reduced or missing aristae",
        "dominance": "recessive",
        "display_label": "al",
        "phenotype_key": "al",
        "chromosome": 2,
        "scoring_confidence": 0.72,
        "gene_name": "aristaless",
        "flybase_id": "FBgn0000061",
        "reference_url": "https://flybase.org/reports/FBgn0000061.html",
        "source": "manual_dictionary",
    },
    "ca": {
        "body_part": "eye",
        "effect": "wine-red eye color",
        "dominance": "recessive",
        "display_label": "ca",
        "phenotype_key": "ca",
        "chromosome": 3,
        "scoring_confidence": 0.86,
        "gene_name": "claret",
        "flybase_id": "FBgn0000247",
        "reference_url": "https://flybase.org/reports/FBgn0000247.html",
        "source": "manual_dictionary",
    },
    "bw": {
        "body_part": "eye",
        "effect": "brown eye pigment",
        "dominance": "recessive",
        "display_label": "bw",
        "phenotype_key": "bw",
        "chromosome": 2,
        "scoring_confidence": 0.82,
        "source": "manual_dictionary",
    },
    "car": {
        "body_part": "eye",
        "effect": "carnation eye color",
        "dominance": "recessive",
        "display_label": "car",
        "phenotype_key": "car",
        "chromosome": 1,
        "scoring_confidence": 0.74,
        "source": "manual_dictionary",
    },
    "cn": {
        "body_part": "eye",
        "effect": "cinnabar eye color",
        "dominance": "recessive",
        "display_label": "cn",
        "phenotype_key": "cn",
        "chromosome": 2,
        "scoring_confidence": 0.83,
        "source": "manual_dictionary",
    },
    "cu": {
        "body_part": "wing",
        "effect": "wings curved upward",
        "dominance": "recessive",
        "display_label": "cu",
        "phenotype_key": "cu",
        "chromosome": 3,
        "scoring_confidence": 0.83,
        "gene_name": "curled",
        "flybase_id": "FBgn0261808",
        "reference_url": "https://flybase.org/reports/FBgn0261808.html",
        "source": "manual_dictionary",
    },
    "ct": {
        "body_part": "wing",
        "effect": "cut wing margin with missing margin tissue",
        "dominance": "recessive",
        "display_label": "ct",
        "phenotype_key": "ct",
        "chromosome": 1,
        "scoring_confidence": 0.84,
        "gene_name": "cut",
        "flybase_id": "FBgn0004198",
        "reference_url": "https://flybase.org/reports/FBgn0004198.html",
        "source": "manual_dictionary",
    },
    "cv": {
        "body_part": "wing",
        "effect": "missing crossveins",
        "dominance": "recessive",
        "display_label": "cv",
        "phenotype_key": "cv",
        "chromosome": 3,
        "scoring_confidence": 0.68,
        "gene_name": "crossveinless",
        "flybase_id": "FBgn0000394",
        "reference_url": "https://flybase.org/reports/FBgn0000394.html",
        "source": "manual_dictionary",
    },
    "e": {
        "body_part": "body",
        "effect": "ebony body color",
        "dominance": "recessive",
        "display_label": "e",
        "phenotype_key": "e",
        "chromosome": 3,
        "scoring_confidence": 0.86,
        "source": "manual_dictionary",
    },
    "ey": {
        "body_part": "eye",
        "effect": "eye morphology marker",
        "dominance": "recessive",
        "display_label": "ey",
        "phenotype_key": "ey",
        "chromosome": 4,
        "scoring_confidence": 0.56,
        "source": "manual_dictionary",
    },
    "hry": {
        "body_part": "wing",
        "effect": "ectopic wing hairs and bristles",
        "dominance": "recessive",
        "display_label": "hry",
        "phenotype_key": "hry",
        "chromosome": 3,
        "scoring_confidence": 0.78,
        "gene_name": "hairy",
        "flybase_id": "FBgn0001168",
        "reference_url": "https://flybase.org/reports/FBgn0001168.html",
        "source": "manual_dictionary",
    },
    "f": {
        "body_part": "bristle",
        "effect": "dominant abnormal thoracic macrochaetae",
        "dominance": "recessive",
        "display_label": "f",
        "phenotype_key": "f",
        "chromosome": 1,
        "scoring_confidence": 0.79,
        "source": "manual_dictionary",
    },
    "mwh": {
        "body_part": "wing",
        "effect": "multiple hairs per wing cell",
        "dominance": "recessive",
        "display_label": "mwh",
        "phenotype_key": "mwh",
        "chromosome": 3,
        "scoring_confidence": 0.58,
        "gene_name": "multiple wing hairs",
        "flybase_id": "FBgn0264272",
        "reference_url": "https://flybase.org/reports/FBgn0264272.html",
        "source": "manual_dictionary",
    },
    "lt": {
        "body_part": "eye",
        "effect": "lightened eye pigment",
        "dominance": "recessive",
        "display_label": "lt",
        "phenotype_key": "lt",
        "chromosome": 2,
        "scoring_confidence": 0.72,
        "gene_name": "light",
        "flybase_id": "FBgn0002566",
        "reference_url": "https://flybase.org/reports/FBgn0002566.html",
        "source": "manual_dictionary",
    },
    "nub": {
        "body_part": "wing",
        "effect": "reduced nubbin wings",
        "dominance": "recessive",
        "display_label": "nub",
        "phenotype_key": "nub",
        "chromosome": 2,
        "scoring_confidence": 0.8,
        "gene_name": "nubbin",
        "flybase_id": "FBgn0085424",
        "reference_url": "https://flybase.org/reports/FBgn0085424.html",
        "source": "manual_dictionary",
    },
    "p": {
        "body_part": "eye",
        "effect": "prune eye color",
        "dominance": "recessive",
        "display_label": "p",
        "phenotype_key": "p",
        "chromosome": 3,
        "scoring_confidence": 0.81,
        "gene_name": "prune",
        "flybase_id": "FBgn0086679",
        "reference_url": "https://flybase.org/reports/FBgn0086679.html",
        "source": "manual_dictionary",
    },
    "pr": {
        "body_part": "eye",
        "effect": "purple eye pigment",
        "dominance": "recessive",
        "display_label": "pr",
        "phenotype_key": "pr",
        "chromosome": 2,
        "scoring_confidence": 0.79,
        "gene_name": "purple",
        "flybase_id": "FBgn0003141",
        "reference_url": "https://flybase.org/reports/FBgn0003141.html",
        "source": "manual_dictionary",
    },
    "red": {
        "body_part": "eye",
        "effect": "bright red eye color",
        "dominance": "recessive",
        "display_label": "red",
        "phenotype_key": "red",
        "chromosome": 3,
        "scoring_confidence": 0.82,
        "gene_name": "red",
        "flybase_id": "FBgn0285913",
        "reference_url": "https://flybase.org/reports/FBgn0285913.html",
        "source": "manual_dictionary",
    },
    "px": {
        "body_part": "wing",
        "effect": "plexus wing venation",
        "dominance": "recessive",
        "display_label": "px",
        "phenotype_key": "px",
        "chromosome": 2,
        "scoring_confidence": 0.66,
        "source": "manual_dictionary",
    },
    "ry": {
        "body_part": "eye",
        "effect": "rosy eye color",
        "dominance": "recessive",
        "display_label": "ry",
        "phenotype_key": "ry",
        "chromosome": 3,
        "scoring_confidence": 0.72,
        "gene_name": "rosy",
        "flybase_id": "FBgn0003308",
        "reference_url": "https://flybase.org/reports/FBgn0003308.html",
        "source": "manual_dictionary",
    },
    "ru": {
        "body_part": "eye",
        "effect": "rough eye surface",
        "dominance": "recessive",
        "display_label": "ru",
        "phenotype_key": "ru",
        "chromosome": 3,
        "scoring_confidence": 0.77,
        "gene_name": "roughoid",
        "flybase_id": "FBgn0003295",
        "reference_url": "https://flybase.org/reports/FBgn0003295.html",
        "source": "manual_dictionary",
    },
    "sc": {
        "body_part": "bristle",
        "effect": "missing or reduced macrochaetae",
        "dominance": "recessive",
        "display_label": "sc",
        "phenotype_key": "sc",
        "chromosome": 1,
        "scoring_confidence": 0.62,
        "gene_name": "scute",
        "flybase_id": "FBgn0004170",
        "reference_url": "https://flybase.org/reports/FBgn0004170.html",
        "source": "manual_dictionary",
    },
    "sev": {
        "body_part": "eye",
        "effect": "rough eyes with missing R7 photoreceptors",
        "dominance": "recessive",
        "display_label": "sev",
        "phenotype_key": "sev",
        "chromosome": 3,
        "scoring_confidence": 0.55,
        "gene_name": "sevenless",
        "flybase_id": "FBgn0003366",
        "reference_url": "https://flybase.org/reports/FBgn0003366.html",
        "source": "manual_dictionary",
    },
    "sn": {
        "body_part": "bristle",
        "effect": "singed bristles",
        "dominance": "recessive",
        "display_label": "sn",
        "phenotype_key": "sn",
        "chromosome": 1,
        "scoring_confidence": 0.82,
        "source": "manual_dictionary",
    },
    "speck": {
        "body_part": "body",
        "effect": "speckled dark body spots",
        "dominance": "recessive",
        "display_label": "speck",
        "phenotype_key": "speck",
        "chromosome": 2,
        "scoring_confidence": 0.73,
        "gene_name": "speck",
        "flybase_id": "FBgn0287831",
        "reference_url": "https://flybase.org/reports/FBgn0287831.html",
        "source": "manual_dictionary",
    },
    "st": {
        "body_part": "eye",
        "effect": "scarlet eye color",
        "dominance": "recessive",
        "display_label": "st",
        "phenotype_key": "st",
        "chromosome": 3,
        "scoring_confidence": 0.83,
        "source": "manual_dictionary",
    },
    "sr": {
        "body_part": "wing",
        "effect": "abnormal wing posture or flight from tendon defects",
        "dominance": "recessive",
        "display_label": "sr",
        "phenotype_key": "sr",
        "chromosome": 3,
        "scoring_confidence": 0.68,
        "gene_name": "stripe",
        "flybase_id": "FBgn0003499",
        "reference_url": "https://flybase.org/reports/FBgn0003499.html",
        "source": "manual_dictionary",
    },
    "vg": {
        "body_part": "wing",
        "effect": "vestigial wings",
        "dominance": "recessive",
        "display_label": "vg",
        "phenotype_key": "vg",
        "chromosome": 2,
        "scoring_confidence": 0.88,
        "source": "manual_dictionary",
    },
    "v": {
        "body_part": "eye",
        "effect": "vermilion eye color",
        "dominance": "recessive",
        "display_label": "v",
        "phenotype_key": "v",
        "chromosome": 1,
        "scoring_confidence": 0.87,
        "gene_name": "vermilion",
        "flybase_id": "FBgn0003965",
        "reference_url": "https://flybase.org/reports/FBgn0003965.html",
        "source": "manual_dictionary",
    },
    "w": {
        "body_part": "eye",
        "effect": "white eyes",
        "dominance": "recessive",
        "display_label": "w",
        "phenotype_key": "w_loss",
        "chromosome": 1,
        "scoring_confidence": 0.96,
        "source": "manual_dictionary",
    },
    "wa": {
        "body_part": "eye",
        "effect": "white-apricot eye color",
        "dominance": "recessive",
        "display_label": "wa",
        "phenotype_key": "wa",
        "chromosome": 1,
        "scoring_confidence": 0.71,
        "gene_name": "white-apricot",
        "source": "manual_dictionary",
    },
    "y": {
        "body_part": "body",
        "effect": "yellow body color",
        "dominance": "recessive",
        "display_label": "y",
        "phenotype_key": "y",
        "chromosome": 1,
        "scoring_confidence": 0.9,
        "source": "manual_dictionary",
    },
}


ALLELE_VISUAL_MARKER_DICTIONARY = {
    "Bl[1]": {
        "gene_stem": "Bl",
        "body_part": "bristle",
        "effect": "dominant abnormal thoracic macrochaetae",
        "dominance": "dominant",
        "display_label": "Bl",
        "phenotype_key": "Bl_1",
        "chromosome": 2,
        "scoring_confidence": 0.77,
        "gene_name": "Bristle",
        "flybase_id": "FBgn0000193",
        "reference_url": "https://flybase.org/reports/FBgn0000193.html",
        "source": "manual_dictionary",
    },
    "Kr[If-1]": {
        "gene_stem": "Kr",
        "body_part": "eye",
        "effect": "irregular rough eye facets",
        "dominance": "dominant",
        "display_label": "If",
        "phenotype_key": "Kr_If",
        "chromosome": 2,
        "scoring_confidence": 0.74,
        "gene_name": "Kruppel",
        "flybase_id": "FBgn0001325",
        "reference_url": "https://flybase.org/reports/FBgn0001325.html",
        "source": "manual_dictionary",
    },
    "wg[Gla-1]": {
        "gene_stem": "wg",
        "body_part": "eye",
        "effect": "glazed rough eyes with abnormal pigmentation",
        "dominance": "dominant",
        "display_label": "Gla",
        "phenotype_key": "wg_Gla",
        "chromosome": 2,
        "scoring_confidence": 0.76,
        "gene_name": "wingless",
        "flybase_id": "FBgn0284084",
        "reference_url": "https://flybase.org/reports/FBgn0284084.html",
        "source": "manual_dictionary",
    },
    "wg[Sp-1]": {
        "gene_stem": "wg",
        "body_part": "wing",
        "effect": "spade-shaped notched wings",
        "dominance": "dominant",
        "display_label": "Sp",
        "phenotype_key": "wg_Sp",
        "chromosome": 2,
        "scoring_confidence": 0.78,
        "gene_name": "wingless",
        "flybase_id": "FBgn0284084",
        "reference_url": "https://flybase.org/reports/FBgn0284084.html",
        "source": "manual_dictionary",
    },
    "Dr[Mio]": {
        "gene_stem": "Dr",
        "body_part": "eye",
        "effect": "reduced drop-shaped eyes with locomotor defects",
        "dominance": "dominant",
        "display_label": "Mio",
        "phenotype_key": "Dr_Mio",
        "chromosome": 3,
        "scoring_confidence": 0.75,
        "gene_name": "Drop",
        "flybase_id": "FBgn0000492",
        "reference_url": "https://flybase.org/reports/FBgn0000492.html",
        "source": "manual_dictionary",
    },
    "amos[Roi-1]": {
        "gene_stem": "amos",
        "body_part": "eye",
        "effect": "roughoid eye morphology",
        "dominance": "dominant",
        "display_label": "Roi",
        "phenotype_key": "amos_Roi",
        "chromosome": 2,
        "scoring_confidence": 0.73,
        "gene_name": "amos",
        "source": "manual_dictionary",
    },
    "PPO1[Bc]": {
        "gene_stem": "PPO1",
        "body_part": "body",
        "effect": "black-cells larval body phenotype",
        "dominance": "dominant",
        "display_label": "Bc",
        "phenotype_key": "PPO1_Bc",
        "chromosome": 2,
        "scoring_confidence": 0.72,
        "gene_name": "prophenoloxidase 1",
        "source": "manual_dictionary",
    },
    "l(2)me[1]": {
        "gene_stem": "l(2)me",
        "body_part": "eye",
        "effect": "eye morphology phenotype",
        "dominance": "recessive",
        "display_label": "me",
        "phenotype_key": "l2me_1",
        "chromosome": 2,
        "scoring_confidence": 0.55,
        "source": "manual_dictionary",
    },
    "sna[Sco]": {
        "gene_stem": "sna",
        "body_part": "bristle",
        "effect": "ectopic thoracic bristles",
        "dominance": "dominant",
        "display_label": "Sco",
        "phenotype_key": "sna_Sco",
        "chromosome": 2,
        "scoring_confidence": 0.73,
        "gene_name": "snail",
        "flybase_id": "FBgn0003448",
        "reference_url": "https://flybase.org/reports/FBgn0003448.html",
        "source": "manual_dictionary",
    },
    "sr[1]": {
        "gene_stem": "sr",
        "body_part": "wing",
        "effect": "flightless wings from defective tendon attachment",
        "dominance": "recessive",
        "display_label": "sr",
        "phenotype_key": "sr_1",
        "chromosome": 3,
        "scoring_confidence": 0.79,
        "gene_name": "stripe",
        "flybase_id": "FBgn0003499",
        "reference_url": "https://flybase.org/reports/FBgn0003499.html",
        "source": "manual_dictionary",
    },
}


REVIEWED_MARKER_ALIASES = {
    "Gla": {"alias_type": "allele_token", "value": "wg[Gla-1]"},
    "If": {"alias_type": "allele_token", "value": "Kr[If-1]"},
    "Mio": {"alias_type": "allele_token", "value": "Dr[Mio]"},
    "OrCo-LexA": {"alias_type": "construct_token", "value": "P{Orco-LexA-VP16}unspecified"},
    "Orco-LexA": {"alias_type": "construct_token", "value": "P{Orco-LexA-VP16}unspecified"},
    "Sco": {"alias_type": "allele_token", "value": "sna[Sco]"},
    "w-": {"alias_type": "allele_token", "value": "w[*]"},
}


def _balancer_metadata(symbol, chromosome, default_markers, *, family=None, notes=None):
    return {
        "symbol": symbol,
        "family": family or symbol,
        "chromosome": chromosome,
        "default_markers": list(default_markers),
        "notes": list(notes or []),
        "source": "bdsc_cheat_sheet",
    }


BALANCER_METADATA = {
    "Basc": _balancer_metadata("Basc", 1, ["sc", "Bar"], family="Basc"),
    "Bascy": _balancer_metadata("Bascy", 1, ["y", "sc", "Bar"], family="Basc"),
    "Binsc": _balancer_metadata("Binsc", 1, ["sc", "Bar"], family="Binsc"),
    "Binscy": _balancer_metadata("Binscy", 1, ["y", "sc", "Bar"], family="Binsc"),
    "Binsinscy": _balancer_metadata("Binsinscy", 1, ["y", "sc", "sn", "Bar"], family="Binsc"),
    "CxD": _balancer_metadata(
        "CxD",
        3,
        ["D"],
        family="CxD",
        notes=["Modeled as a third-chromosome dominant marker balancer shorthand."],
    ),
    "CyO": _balancer_metadata(
        "CyO",
        2,
        ["Cy", "pr", "cn"],
        family="CyO",
        notes=["Uses the cheat-sheet visible-marker set for the common second-chromosome balancer."],
    ),
    "FM0": _balancer_metadata("FM0", 1, ["y", "sc", "v", "f", "Bar"], family="FM0"),
    "FM3": _balancer_metadata("FM3", 1, ["y", "sc", "Bar"], family="FM3"),
    "FM4": _balancer_metadata("FM4", 1, ["y", "sc", "Bar"], family="FM4"),
    "FM6": _balancer_metadata("FM6", 1, ["y", "sc", "Bar"], family="FM6"),
    "FM7": _balancer_metadata(
        "FM7",
        1,
        ["Bar"],
        family="FM7",
        notes=["Bare FM7 is kept conservative; specific FM7 variants carry the fuller cheat-sheet marker sets."],
    ),
    "FM7a": _balancer_metadata("FM7a", 1, ["y", "sc", "Bar"], family="FM7"),
    "FM7b": _balancer_metadata("FM7b", 1, ["y", "sc", "Bar"], family="FM7"),
    "FM7c": _balancer_metadata(
        "FM7c",
        1,
        ["y", "sc", "sn", "Bar"],
        family="FM7",
        notes=["Preserves the FM7c-specific sn marker instead of collapsing to generic FM7."],
    ),
    "FM7d": _balancer_metadata("FM7d", 1, ["sc", "Bar"], family="FM7"),
    "FM7h": _balancer_metadata("FM7h", 1, ["sc", "Bar"], family="FM7"),
    "FM7i": _balancer_metadata("FM7i", 1, ["sc", "Bar"], family="FM7"),
    "FM7j": _balancer_metadata("FM7j", 1, ["y", "sc"], family="FM7"),
    "FM7k": _balancer_metadata("FM7k", 1, ["y", "sc", "sn", "Bar"], family="FM7"),
    "MKRS": _balancer_metadata("MKRS", 3, ["ry", "Sb"], family="MKRS"),
    "MRS": _balancer_metadata(
        "MRS",
        3,
        ["ry", "Sb"],
        family="MKRS",
        notes=["Treated as the same visible-marker set as MKRS for phenotype summaries."],
    ),
    "SM1": _balancer_metadata("SM1", 2, ["al", "Cy", "cn", "speck"], family="SM1"),
    "SM5": _balancer_metadata("SM5", 2, ["al", "Cy", "lt", "cn", "speck"], family="SM5"),
    "SM6a": _balancer_metadata("SM6a", 2, ["al", "Cy", "cn", "speck"], family="SM6"),
    "SM6b": _balancer_metadata("SM6b", 2, ["al", "Cy", "cn", "speck"], family="SM6"),
    "TM1": _balancer_metadata("TM1", 3, ["Sb"], family="TM1"),
    "TM2": _balancer_metadata("TM2", 3, ["e"], family="TM2"),
    "TM3": _balancer_metadata(
        "TM3",
        3,
        ["p", "Ubx", "e"],
        family="TM3",
        notes=[
            "Bare TM3 follows the conservative BDSC core visible-marker set.",
            "Explicit Sb[1] and Ser[1] in genotype strings are resolved separately rather than implied by TM3.",
        ],
    ),
    "TM6": _balancer_metadata("TM6", 3, ["Hu", "Tb", "e"], family="TM6"),
    "TM6B": _balancer_metadata("TM6B", 3, ["Hu", "Tb", "e"], family="TM6"),
    "TM6C": _balancer_metadata(
        "TM6C",
        3,
        ["e"],
        family="TM6",
        notes=["Uses the stripped-down TM6C visible core from the cheat sheet rather than the fuller TM6B shorthand."],
    ),
    "TM8": _balancer_metadata("TM8", 3, ["st", "Sb", "e"], family="TM8"),
    "TM9": _balancer_metadata("TM9", 3, ["st", "Sb", "e"], family="TM9"),
    "TMS": _balancer_metadata("TMS", 3, ["ry", "Sb"], family="TMS"),
    "winscy": _balancer_metadata("winscy", 1, ["y", "sc"], family="winscy"),
}


BALANCER_ALIASES = {
    "Binsn": "Binsc",
    "FM6B": "FM6",
}


for alias_symbol, canonical_symbol in BALANCER_ALIASES.items():
    BALANCER_METADATA.setdefault(canonical_symbol, {}).setdefault("aliases", []).append(alias_symbol)


BALANCER_MARKERS = {
    symbol: list(metadata["default_markers"])
    for symbol, metadata in BALANCER_METADATA.items()
}


KNOWN_BALANCER_SYMBOLS = set(BALANCER_METADATA) | set(BALANCER_ALIASES)


def get_balancer_metadata(symbol):
    canonical_symbol = BALANCER_ALIASES.get(str(symbol or "").strip(), str(symbol or "").strip())
    metadata = BALANCER_METADATA.get(canonical_symbol)
    if metadata is None:
        return None
    return deepcopy(metadata)


def get_visual_marker(symbol, allele_spec=None, token=None):
    allele_key = None
    if token and token in ALLELE_VISUAL_MARKER_DICTIONARY:
        allele_key = token
    elif symbol and allele_spec:
        candidate_key = f"{symbol}[{allele_spec}]"
        if candidate_key in ALLELE_VISUAL_MARKER_DICTIONARY:
            allele_key = candidate_key

    if allele_key is not None:
        marker = deepcopy(ALLELE_VISUAL_MARKER_DICTIONARY[allele_key])
        marker.setdefault("gene_stem", symbol)
        marker["allele_specific"] = True
        marker["allele_token"] = allele_key
        return marker

    entry = VISUAL_MARKER_DICTIONARY.get(symbol)
    if entry is None:
        return None
    marker = deepcopy(entry)
    marker["gene_stem"] = symbol
    return marker


def get_reviewed_marker_alias(alias_token):
    return deepcopy(REVIEWED_MARKER_ALIASES.get(str(alias_token or "").strip()))
